name: Test

on: 
    push:
        branches: [main]

jobs: 
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Log repo
              run: echo 'Repo name = $GITHUB_REPOSITORY'